'''
utilities.py

stores any functions that should be used across all systems in a local manner
'''

#imports

# struct target

def parser(path, inpu):
    length = 0
    seconds = 0
    file = open(path+inpu)
    use = ''
    for i in file():
        use=use + i.read
    return inp

'''

checks that the input matches the expected type
generated by an explicit declairaiton of the desired system
for example 'str' or array[]
'''
def check_input(expected, recieved):
    ret = False
    if isinstance(expected) == isinstance(recieved):
        ret = True

    return ret
