'''
utilities.py

stores any functions that should be used across all systems in a local manner
'''

#imports
import subprocess
# struct target

def parser(path, inpu):
    '''
    Creator: Tate Bowers
    Input: takes in a file and its path
    Output: returns the data of that file
    This function is a Generalized parser
    sort of implemented in main, might need to differentiate someway in the future
    keeping because no real reason to remove
    '''

    file = open(path+'\\'+inpu)
    use = ''
    for i in file():
        use = use + i.read
    return use


def check_input(expected, recieved):
    '''
    Creator: Tate Bowers
    Input: example of the expected file type, what was recieved
    Output: whether or not the two are equal (if the file is what is expected)
    This function checks that the input matches the expected type
    generated by an explicit declairaiton of the desired system
    for example 'str' or list[]
    '''
    ret = False
    #print(type(recieved))
    if isinstance(recieved, type(expected)): #== isinstance(recieved):
        ret = True

    return ret



def create_child(inp, other_arguments):
    '''
    Creator: Tate Bowers
    Input: process name
    Output: connection to child input/output
    This function takes in a file to run and runs it,
    passing in the output and input to a location that you can use
    TODO figure out how to properly sync error logging
    inp

    '''
    ret = -1
    if check_input('str', inp):
        if check_input('str', other_arguments): #can be a str or array, probably should be str
            run = 'python '+inp+'.py '+other_arguments
            try:
                ret = subprocess.Popen(run, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
                    #send stdout to buffer, to write to log
            except ChildProcessError:
                print('scream and run')
                #run debug process and try again later
                #logBuffer = logBuffer + "UI Error: Failed to init"
                #try this
                    #try
                    #except ChildProcessError
                    #except as otr: again
                #seems like it would be a good idea to push this to a function.
            #except:
                #something else went wrong, try to make better
                #logBuffer=logBuffer+"UI Error: " + sys.exc_info()[0]#think this is the syntax

    return ret
